server:
  port: 8080
  servlet:
    context-path: /mytest/
spring:
  mvc:
    view:
      prefix: /page/
      suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: springboot
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.liangxin.springboot.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl